services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: johnny
      POSTGRES_DB: crmdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/pg

volumes:
  postgres_data:
